### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by AlexanderYAntonov** [cft-group/elephas-angular#7]
During compilation has next error:

ERROR in node_modules/@elephas/angular/base-input/base-input.d.ts(47,18): error TS2304: Cannot find name 'InputEvent'

(in my app I use only ElDataListModule and ElBannerModule)

![image](https://user-images.githubusercontent.com/34083819/81798885-baa15b00-953a-11ea-92b5-79175d01e2ec.png)

**Comment by apust** [comment]
@Amil-Gaoul, не знаешь, с чем может быть связано?

**Comment by apust** [comment]
@AlexanderYAntonov, можешь, пожалуйста, сообщить контекст, чтобы можно было воспроизвести ошибку? Версия Angular, как собираешь приложение и т.д.

**Comment by AlexanderYAntonov** [comment]
package.json:
 `{
  ...,
  "dependencies": {
    "@angular/animations": "^8.0.1",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "^8.0.1",
    "@angular/compiler": "^8.0.1",
    "@angular/core": "^8.0.1",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "^8.0.1",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.0.1",
    "@angular/material-moment-adapter": "^8.0.1",
    "@angular/platform-browser": "^8.0.1",
    "@angular/platform-browser-dynamic": "^8.0.1",
    "@angular/router": "^8.0.1",
    "@elephas/angular": "^0.2.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/js-base64": "^2.3.1",
    "angular": "^1.7.9",
    "core-js": "^2.6.9",
    "js-base64": "^2.5.1",
    "keycloak-angular": "^6.1.0",
    "material-design-icons-iconfont": "^5.0.1",
    "moment": "^2.24.0",
    "ngx-loading": "^1.0.15",
    "popper.js": "^1.15.0",
    "rxjs": "^6.5.2",
    "stream": "0.0.2",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.25",
    "@angular/cli": "^8.0.3",
    "@angular/compiler-cli": "^8.0.1",
    "@angular/language-service": "^8.0.1",
    "@types/jasmine": "^2.8.16",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "^6.0.118",
    "codelyzer": "^5.1.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.2.0",
    "karma-chrome-launcher": "^3.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "node-sass": "^4.13.1",
    "protractor": "^5.4.2",
    "ts-node": "~5.0.1",
    "tslint": "~5.11.0",
    "typescript": "^3.4.5"
  }
}
`

aml.module.ts:
`import { NgModule } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { FlexLayoutModule } from '@angular/flex-layout';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  MatButtonModule,
  MatCardModule,
  MatDatepickerModule,
  MatDialogModule,
  MatFormFieldModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSidenavModule,
  MatTableModule,
  MatToolbarModule,
  MatTooltipModule
} from '@angular/material';
import { MatBadgeModule } from '@angular/material/badge';
import { MatMomentDateModule } from '@angular/material-moment-adapter';
import { LoadingModule } from 'ngx-loading';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AmlBaseComponent, HomeComponent } from '@app/aml/containers';
import { MessageService } from '@app/message.service';
import { AmlRoutingModule } from '@app/aml/aml-routing.module';
import { AuthModule } from '@app/auth/auth.module';
import { BreadCrumbsService } from '@app/bread-crumbs.service';
import { ElDataListModule, ElBannerModule } from '@elephas/angular';

@NgModule({
  imports: [
    AuthModule,
    CommonModule,
    AmlRoutingModule,
    HttpClientModule,
    MatSidenavModule,
    BrowserAnimationsModule,
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatNativeDateModule,
    MatInputModule,
    MatToolbarModule,
    MatListModule,
    MatCardModule,
    FormsModule,
    ReactiveFormsModule,
    MatDialogModule,
    MatGridListModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatMomentDateModule,
    MatTableModule,
    LoadingModule,
    FlexLayoutModule,
    MatBadgeModule,
    MatTooltipModule,
    ElDataListModule,
    ElBannerModule
  ],
  declarations: [AmlBaseComponent, HomeComponent],
  exports: [],
  providers: [HttpClientModule, DatePipe, MessageService, BreadCrumbsService],
  entryComponents: []
})
export class AmlModule {}
`

![image](https://user-images.githubusercontent.com/34083819/82026750-5fe43c80-96bd-11ea-8e26-2b993f1f1060.png)

**Comment by apust** [comment]
Angular 8, а у нас библиотека под Angular 9.

**Comment by AlexanderYAntonov** [comment]
В AML используется angular-slickgrid, который не поддерживает Angular 9.
